[secrets]
build_flags =
  ; Uncomment to enable Serial debug logging.
  ; -D DEBUG_SERIAL
  -D WIFI_SSID=\"your-wifi-ssid\"
  -D WIFI_PASSWORD=\"your-wifi-password\"
  -D PROXY_SERVER=192,168,7,61
  -D PROXY_PORT=3333
